"""add current_step_index to task

Revision ID: 81d0ebd54177
Revises: 9c37802d27fd
Create Date: 2024-11-12 17:17:19.258263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '81d0ebd54177'
down_revision: Union[str, None] = '9c37802d27fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('current_step_index', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'dialogue')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('dialogue', sqlite.JSON(), nullable=True))
    op.drop_column('tasks', 'current_step_index')
    # ### end Alembic commands ###
